#!/bin/sh
### BEGIN INIT INFO
# Provides:		barbot
# Required-Start:	$syslog $remote_fs $network
# Required-Stop:	$syslog	$remote_fs $network
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	barbot
# Description:		barbot
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/web/barbot/api/scripts/barbot-daemon.php
NAME=barbot
RUNDIR=/var/run/barbot
PIDFILE=$RUNDIR/barbot.pid

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
    echo -n "Starting $NAME: "
    mkdir -p $RUNDIR
    touch $PIDFILE
    chown pi:pi $RUNDIR $PIDFILE
    chmod 755 $RUNDIR

    if start-stop-daemon --start --background --quiet --umask 007 --pidfile $PIDFILE --chuid pi:pi --exec $DAEMON -- 
    then
      echo "$NAME."
    else
      echo "failed"
    fi
    ;;

  stop)
    echo -n "Stopping $NAME: "
    if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
    then
      echo "$NAME."
    else
      echo "failed"
    fi
    rm -f $PIDFILE
    sleep 1
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;

  status)
    echo -n "$DESC is "
    if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
    then
            echo "running"
    else
            echo "not running"
            exit 1
    fi
    ;;
        
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0

